# Generated by Django 3.2.9 on 2021-11-13 11:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'File Categories',
            },
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('file_media_link', models.FileField(blank=True, upload_to='files')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='created_on,file_name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanagement.filecategory')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanagement.departmentmodel')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ['created_on'],
            },
        ),
    ]
